package com.marketplace.shared.exception;

public enum ErrorCode {
    VALIDATION_ERROR,
    RESOURCE_NOT_FOUND,
    BUSINESS_RULE_VIOLATION,
    CONCURRENCY_CONFLICT,
    UNAUTHORIZED,
    FORBIDDEN,
    INSUFFICIENT_INVENTORY,
    COUPON_INVALID_OR_EXPIRED,
    PAYMENT_FAILED,
    SELLER_NOT_APPROVED,
    IDEMPOTENCY_CONFLICT,
    INTERNAL_SERVER_ERROR
}
